#+title: Notes

* Cub3d project [0/0]
** TODO Tasks
*** TODO Parsing
**** DONE Maps
CLOSED: [2025-10-07 Tue 10:22]
**** TODO preamble
***** TODO RGB to int conversion
***** TODO Clean up of config struct
***** TODO


* parsing

I have completed the parsing of maps, including basic validation. this means
only maps that contain valid chars, and one and only one player char are
permitted.

it also allows for one and only one of each texture (NESW) and colour (FC)
order does not matter, nor empty lines etc.

what needs to be done:


TODOs

DINIS:
        add copy of sprites for cigarettes.
        # handle segfault in cleanup function.
        do a map (sailor moon)
        the doors
        check flood fill still works with the D (should reject if D is touching
        void)

       


WILLIAM:
        create smoke particles
        norm compliance on files
        add a exception to the parser to handle D as input (only in bonus)
        rotate origin of player to corresponding cardinality
        do a map
